// ~ Generated by TestSpec.SyntaticSugar.tt
using System;
using System.Threading.Tasks;
using Xunit;
using Xunit.Abstractions;

namespace Layman
{
    partial class TestSpec
    {
        protected void And(string description, Func<bool> check)
        {
            It(description, check);
        }

        protected void That(string description, Func<bool> check)
        {
            It(description, check);
        }

        protected void Then(string description, Func<bool> check)
        {
            It(description, check);
        }

        protected void And(string description, bool outcome)
        {
            It(description, outcome);
        }

        protected void That(string description, bool outcome)
        {
            It(description, outcome);
        }

        protected void Then(string description, bool outcome)
        {
            It(description, outcome);
        }

        protected async Task And(string description, Func<Task> asyncAction)
        {
            await It(description, asyncAction);
        }

        protected async Task That(string description, Func<Task> asyncAction)
        {
            await It(description, asyncAction);
        }

        protected async Task Then(string description, Func<Task> asyncAction)
        {
            await It(description, asyncAction);
        }

        protected void And(string description, Action check)
        {
            It(description, check);
        }

        protected void That(string description, Action check)
        {
            It(description, check);
        }

        protected void Then(string description, Action check)
        {
            It(description, check);
        }

        protected void And(Action check)
        {
            It(check);
        }

        protected void That(Action check)
        {
            It(check);
        }

        protected void Then(Action check)
        {
            It(check);
        }

        protected void And(string description)
        {
            It(description);
        }

        protected void That(string description)
        {
            It(description);
        }

        protected void Then(string description)
        {
            It(description);
        }

    }
}
