// ~ Generated by TestSpec.SyntaticSugar.tt
using System;
using Xunit;

namespace Layman
{
    partial class TestSpec
    {
        protected void And(string description, Func<bool> check)
        {
            It(description, check);
        }

        protected void That(string description, Func<bool> check)
        {
            It(description, check);
        }

        protected void Then(string description, Func<bool> check)
        {
            It(description, check);
        }

        protected void And(string description, Action check)
        {
            It(description, check);
        }

        protected void That(string description, Action check)
        {
            It(description, check);
        }

        protected void Then(string description, Action check)
        {
            It(description, check);
        }

        protected void And(Action check)
        {
            It(check);
        }

        protected void That(Action check)
        {
            It(check);
        }

        protected void Then(Action check)
        {
            It(check);
        }

    }
}
